# -*- coding: utf-8 -*-
"""Dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-j8J6vsGJqtfuhIcLZXDX-OB66WRCc-T
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
bike_data = pd.read_csv('hour.csv')

# Cleaning dataset (as we did before)
bike_data_clean = bike_data.drop(['instant', 'dteday'], axis=1)

# Sidebar configuration
st.sidebar.title("Bike Sharing Analysis Dashboard")
question = st.sidebar.selectbox(
    "Pilih Pertanyaan Bisnis",
    ("Pengaruh Suhu Terhadap Jumlah Penyewaan",
     "Pola Penyewaan Sepeda Berdasarkan Hari Kerja dan Akhir Pekan")
)

# Title
st.title("Bike Sharing Data Analysis")

# Display dataset preview
if st.checkbox("Tampilkan Dataframe"):
    st.write(bike_data.head())

# Question 1: Pengaruh Suhu terhadap Jumlah Penyewaan Sepeda
if question == "Pengaruh Suhu Terhadap Jumlah Penyewaan":
    st.header("Pengaruh Suhu terhadap Jumlah Penyewaan Sepeda")

    # Scatter plot of temperature vs count
    plt.figure(figsize=(10,6))
    sns.scatterplot(x=bike_data_clean['temp'], y=bike_data_clean['cnt'])
    plt.title('Hubungan antara Suhu dan Jumlah Penyewaan Sepeda')
    plt.xlabel('Suhu (Normalized)')
    plt.ylabel('Jumlah Penyewaan Sepeda')

    st.pyplot(plt.gcf())

    # Insight
    st.markdown("""
    **Insight**:
    - Terdapat hubungan positif antara suhu dan jumlah penyewaan sepeda.
    - Semakin tinggi suhu, semakin banyak sepeda yang disewa.
    """)

# Question 2: Pola Penyewaan Berdasarkan Hari Kerja dan Akhir Pekan
elif question == "Pola Penyewaan Sepeda Berdasarkan Hari Kerja dan Akhir Pekan":
    st.header("Pola Penyewaan Berdasarkan Hari Kerja dan Akhir Pekan")

    # Bar plot for working day vs count
    plt.figure(figsize=(8,5))
    sns.barplot(x='workingday', y='cnt', data=bike_data_clean, ci=None)
    plt.title('Penyewaan Sepeda pada Hari Kerja vs Akhir Pekan')
    plt.xticks([0, 1], ['Akhir Pekan', 'Hari Kerja'])
    plt.ylabel('Jumlah Penyewaan Sepeda')

    st.pyplot(plt.gcf())

    # Insight
    st.markdown("""
    **Insight**:
    - Jumlah penyewaan sepeda pada hari kerja lebih tinggi dibandingkan akhir pekan.
    """)

# Additional Analysis: Pengaruh Cuaca terhadap Penyewaan
st.sidebar.subheader("Analisis Tambahan")
if st.sidebar.checkbox("Pengaruh Kondisi Cuaca terhadap Penyewaan"):
    st.header("Pengaruh Kondisi Cuaca terhadap Penyewaan Sepeda")

    # Bar plot for weather situation vs count
    plt.figure(figsize=(10,6))
    sns.barplot(x='weathersit', y='cnt', data=bike_data_clean, ci=None)
    plt.title('Pengaruh Kondisi Cuaca terhadap Jumlah Penyewaan Sepeda')

    st.pyplot(plt.gcf())

    # Insight
    st.markdown("""
    **Insight**:
    - Cuaca juga mempengaruhi penyewaan sepeda, di mana kondisi cuaca yang baik cenderung meningkatkan jumlah penyewaan.
    """)

# Conclusion
st.sidebar.subheader("Kesimpulan")
if st.sidebar.checkbox("Tampilkan Kesimpulan"):
    st.header("Kesimpulan")

    st.markdown("""
    **Kesimpulan**:
    1. Suhu memiliki pengaruh besar terhadap jumlah penyewaan sepeda, semakin tinggi suhu, semakin banyak sepeda yang disewa.
    2. Hari kerja memiliki volume penyewaan yang lebih tinggi dibandingkan akhir pekan.
    3. Cuaca juga mempengaruhi jumlah penyewaan sepeda, di mana kondisi cuaca yang baik meningkatkan jumlah penyewaan.
    """)
